Gauss Jordan y factorizacion LU

https://github.com/Sdann26/Analisis-Numerico/blob/master/Algoritmo%20Tridiagonal.py

https://www.unioviedo.es/compnum/laboratorios_py/sist_lin/sist_lin.html

https://relopezbriega.github.io/blog/2016/09/13/factorizacion-de-matrices-con-python/

checar librp de$\dots$ scott numetical analysis

In [3]:
# Librerías numpy y scipy
from  time  import*
import numpy as np
import pprint
import scipy
import scipy.linalg  

print('MÉTODO LU CON PIVOTEO',end="\n\ n")

print("Este método te halla las matrices L, U y P y cálcula la solución del sistema L * U * X = P * b. Siendo L * U = P * A.\n")

# Coloca la matriz A:
A=np.array([[1,1,0,-1,0],[1,0,0,0,-1],[4,4,1,-2,-4],[0,1,0,0,-2],[0,0,2,0,0]],float)

# Coloca el vector solución b:
b=np.array([[0],[2],[8],[0],[4]],float)


t1=perf_counter(); #Calcula tiempo inicio del algoritmo
# Función LU, aquí se inserta la matriz y su tamaño
P, L, U = scipy.linalg.lu(A)
t2=perf_counter(); #Calcula tiempo final del algoritmo

A = np.array(A,float)
P = np.array(P,float)
L = np.array(L,float)
U = np.array(U,float)

print ("Matriz A:")
pprint.pprint(A)
print ("Matriz P:")
pprint.pprint(np.linalg.inv(P))
print ("Matriz L:")
pprint.pprint(L)
print ("Matriz U:")
pprint.pprint(U)
print("\nVector solución b: \n"+str(b))

print("\nEl tiempo de ejecución es: "+str(t2-t1))

print("\nPrimero, resolvemos L * Y =  P * b:")
L = np.dot(P,L)
y = np.linalg.solve(L,b)
print("La solución de Y es:\n" +str(y))

print("\nLuego desarrollamos U * X = Y:")
x = np.linalg.solve(U,y)
print("La solución de X es: \n"+str(x))

R = x - np.linalg.solve(A,b)

print("\nLa calidad de la solución es:\n")
print(str((np.linalg.norm(R,np.inf)/np.linalg.norm(b,np.inf))*(1/np.linalg.cond(A,np.inf)))+" ≤ ||E||∞/||x||∞ ≤ "+str((np.linalg.norm(R,np.inf)/np.linalg.norm(b,np.inf))*np.linalg.cond(A,np.inf)))

MÉTODO LU CON PIVOTEO
\ nEste método te halla las matrices L, U y P y cálcula la solución del sistema L * U * X = P * b. Siendo L * U = P * A.

Matriz A:
array([[ 1.,  1.,  0., -1.,  0.],
       [ 1.,  0.,  0.,  0., -1.],
       [ 4.,  4.,  1., -2., -4.],
       [ 0.,  1.,  0.,  0., -2.],
       [ 0.,  0.,  2.,  0.,  0.]])
Matriz P:
array([[0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.]])
Matriz L:
array([[ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.25 ,  1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   , -0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.   , -1.   , -0.125,  1.   ,  0.   ],
       [ 0.25 , -0.   , -0.125, -1.   ,  1.   ]])
Matriz U:
array([[ 4.  ,  4.  ,  1.  , -2.  , -4.  ],
       [ 0.  , -1.  , -0.25,  0.5 ,  0.  ],
       [ 0.  ,  0.  ,  2.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.5 , -2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , -1.  ]])

Vector solución b: 
[[0.]
 [2.]

la que tiene unos en la diagonal es L, mientras que la otra no