Un sistema lineal de n ecuiaciones en n variables realies tien la forma:

$a_{11}x_{1} + a_{12}x_2 + \dots a_{1n}x_n = f_1$


$a_{21}x_{1} + a_{22}x_n + \dots a_{2n}x_n = f_2$


$a_{31}x_{1} + a_{32}x_n + \dots a_{3n}x_n = f_3$

$\vdots$


$a_{n1}x_{1} + a_{n2}x_n + \dots a_{nm}x_n = f_n$

In [60]:
import numpy as np
import sympy as sy
import matplotlib.pyplot as plt
from sympy import *
from sympy.abc import x

In [61]:
A=np.random.rand(3,3)

F=np.array([[1],[2],[3]])

C=np.random.randint(10,size=(3,3))

print(A)

print()

print(B)

print()

print(C)

[[0.17253074 0.89772405 0.65924496]
 [0.75268379 0.98330361 0.49243567]
 [0.71938226 0.32183261 0.3635218 ]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[6 2 6]
 [1 7 6]
 [7 2 1]]


In [62]:
#U=np.array
U=np.copy(A)
G=np.copy(F)
def Gauss(A, F, k):
    for i in range (k):
        for j in range (k):
            U[i,j]=A[i,j]-(M[i,k]*A[k,j])
            M[i,k]=(A[i,k]/A[k,k])


https://juncotic.com/metodo-de-heron-algoritmos-antiguos/

juntar la ecuacion trascendete de la hidraulica con la forma de serie de la tangente para usar los numero d ebermnopulli

http://blog.espol.edu.ec/analisisnumerico/metodo-de-gauss-con-python/

In [63]:
def gauss(C,F):
    U=np.copy(C)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range (j+1,n):
            M=U[i,j]/U[j,j]
            U[i,j:]=U[i,j:]-(M*U[j,j:])
            G[i]=G[i]-(M*G[j])
    return (U,G)

In [64]:
print(U,G)

[[0.17253074 0.89772405 0.65924496]
 [0.75268379 0.98330361 0.49243567]
 [0.71938226 0.32183261 0.3635218 ]] [[1]
 [2]
 [3]]
