Un sistema lineal de n ecuiaciones en n variables realies tien la forma:

$a_{11}x_{1} + a_{12}x_2 + \dots a_{1n}x_n = f_1$


$a_{21}x_{1} + a_{22}x_n + \dots a_{2n}x_n = f_2$


$a_{31}x_{1} + a_{32}x_n + \dots a_{3n}x_n = f_3$

$\vdots$


$a_{n1}x_{1} + a_{n2}x_n + \dots a_{nm}x_n = f_n$

In [12]:
import numpy as np
import matplotlib.pyplot as plt

https://juncotic.com/metodo-de-heron-algoritmos-antiguos/

juntar la ecuacion trascendete de la hidraulica con la forma de serie de la tangente para usar los numero d ebermnopulli

http://blog.espol.edu.ec/analisisnumerico/metodo-de-gauss-con-python/

In [42]:
#A=np.random.rand(3,3)

#F=np.array([[1],[2],[3]])

#C=np.random.randint(10,size=(3,3))

#Declaramos dos matrices

A=np.array([[6,-2,2,4],
           [12,-8,6,10],
           [3,-13,9,3],
           [-6,4,1,-18]])

B=np.array([12,34,27,-38])

#imprimimos ambas matrices

print(A)

print()

print(B)

[[  6  -2   2   4]
 [ 12  -8   6  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]

[ 12  34  27 -38]


In [43]:
def Gauss(A,B):
    U=np.copy(A).astype(float) #estos valores son con punto decimal
    G=np.copy(B).astype(float) #estos valores son con punto decimal
    n=B.size
    for j in range(n-1):
        for i in range(j+1,n):
            M=U[i,j]/U[j,j] #un facto M para evitar escribir mucho
            U[i,j:]=U[i,j:]-(M*U[j,j:])
            G[i]=G[i]-(M*G[j])
    return U,G

In [45]:
U=Gauss(A,B)[0]
G=Gauss(A,B)[1]

print(U)
print()
print()
print(G)

#se muestra la diagnalizacion de la matriz

[[ 6. -2.  2.  4.]
 [ 0. -4.  2.  2.]
 [ 0.  0.  2. -5.]
 [ 0.  0.  0. -3.]]


[12. 10. -9. -3.]


In [46]:
#se inicia la solucion de la matriz

def sol(U,G):
    n = G.size
    x = np.zeros(n)
    for i in reversed(range(n)):
        aux=0
        for j in range (i+1,n):
            aux += U[i,j] * x[j]
        x[i] = (G[i] - aux) / U[i, i]
    return x

In [47]:
solucion=sol(U,G)

In [48]:
print(solucion)

[ 1. -3. -2.  1.]
