Un sistema lineal de n ecuiaciones en n variables realies tien la forma:

$a_{11}x_{1} + a_{12}x_2 + \dots a_{1n}x_n = f_1$


$a_{21}x_{1} + a_{22}x_n + \dots a_{2n}x_n = f_2$


$a_{31}x_{1} + a_{32}x_n + \dots a_{3n}x_n = f_3$

$\vdots$


$a_{n1}x_{1} + a_{n2}x_n + \dots a_{nm}x_n = f_n$

In [144]:
import numpy as np
import matplotlib.pyplot as plt

https://juncotic.com/metodo-de-heron-algoritmos-antiguos/

juntar la ecuacion trascendete de la hidraulica con la forma de serie de la tangente para usar los numero d ebermnopulli

http://blog.espol.edu.ec/analisisnumerico/metodo-de-gauss-con-python/

In [166]:
#A=np.random.rand(3,3)

#F=np.array([[1],[2],[3]])

#C=np.random.randint(10,size=(3,3))

A=np.array([[6,-2,2,4],
           [12,-8,6,10],
           [3,-13,9,3],
           [-6,4,1,-18]])

F=np.array([12,34,27,-38])

In [170]:
def Gauss(A,F):
    U=np.copy(A)
    G=np.copy(F)
    n=F.size
    for j in range(n-1):
        for i in range(j+1,n):
            U[i,j:]=U[i,j:]-((U[i,j]/U[j,j])*U[j,j:])
            G[i]=G[i]-((U[i,j]/U[j,j])*G[j])
    return U,G

In [174]:

print("A= ",A)
print()
print()
print("B= ",B)
print()
print()
u=Gauss(A,B)[0]
g=Gauss(A,B)[1]


print("Las soluciones son: \n",u,"\n\n",g)

A=  [[  6  -2   2   4]
 [ 12  -8   6  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]


B=  [ 12  34  27 -38]


Las soluciones son: 
 [[ 6 -2  2  4]
 [ 0 -4  2  2]
 [ 0  0  2 -5]
 [ 0  0  0 -3]] 

 [ 12  34  27 -38]
