Un sistema lineal de n ecuiaciones en n variables realies tien la forma:

$a_{11}x_{1} + a_{12}x_2 + \dots a_{1n}x_n = f_1$


$a_{21}x_{1} + a_{22}x_n + \dots a_{2n}x_n = f_2$


$a_{31}x_{1} + a_{32}x_n + \dots a_{3n}x_n = f_3$

$\vdots$


$a_{n1}x_{1} + a_{n2}x_n + \dots a_{nm}x_n = f_n$

In [46]:
import numpy as np
import matplotlib.pyplot as plt

https://juncotic.com/metodo-de-heron-algoritmos-antiguos/

juntar la ecuacion trascendete de la hidraulica con la forma de serie de la tangente para usar los numero d ebermnopulli

http://blog.espol.edu.ec/analisisnumerico/metodo-de-gauss-con-python/

In [58]:
#A=np.random.rand(3,3)

#F=np.array([[1],[2],[3]])

#C=np.random.randint(10,size=(3,3))

A=np.array([[6,-2,2,4],
           [12,-8,6,10],
           [3,-13,9,3],
           [-6,4,1,-18]])

B=np.array([12,34,27,-38])


print(A)

print()

print(B)

[[  6  -2   2   4]
 [ 12  -8   6  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]

[ 12  34  27 -38]


In [48]:
def Gauss(A,B):
    U=np.copy(A)
    G=np.copy(B)
    n=B.size
    for j in range(n-1):
        for i in range(j+1,n):
            U[i,j:]=U[i,j:]-((U[i,j]/U[j,j])*U[j,j:])
            G[i]=G[i]-((U[i,j]/U[j,j])*G[j])
    return U,G



In [52]:
U=Gauss(A,B)[0]
G=Gauss(A,B)[1]

print(U)
print()
print()
print(G)

[[ 6 -2  2  4]
 [ 0 -4  2  2]
 [ 0  0  2 -5]
 [ 0  0  0 -3]]


[ 12  34  27 -38]


In [56]:
def sol(U,G):
    n = G.size
    x = np.zeros(n)
    aux = 0
    for i in reversed(range(n)):
        if i == (n-1):
            x[i] = (G[i])/(U[i,i])
            continue
        else:
            for j in range (i+1,n):
                aux += U[i,j]*x[j]
            x[i] = (G[i]/U[i,i]) - (1/U[i,i])*aux
            aux = 0
    return x

In [60]:
sol(U,G)

array([-14.69444444,  20.41666667,  45.16666667,  12.66666667])